### ISSUE TITLE
add ESLint

### ISSUE THREAD

**Issue by eslintfan** [sindresorhus/generator-nm#14]
why do you still prefer jshint over eslint? jshint doesn't validate code style :((

**Comment by sindresorhus** [comment]
I'm working on moving over to ESLint. Will update this generator in a couple of weeks. I totally agree.

**Comment by arthurvr** [comment]
:+1:

**Comment by floatdrop** [comment]
I, who always forget space before parenthesis in function statement,  would :heart: this.

**Comment by u4q** [comment]
+1

**Comment by kevva** [comment]
Are we going to move `xo` in here @sindresorhus?

**Comment by sindresorhus** [comment]
@kevva Yes, was planning that. Maybe in a few weeks.
