### ISSUE TITLE
Proposal for more options

### ISSUE THREAD

**Issue by alexbooker** [sindresorhus/generator-nm#21]
Hi :smile:

How would you feel about the addition of these options:

- _"Do you need tests?"_
- _"Do you need a travis.yml file?"_

**Justification**

I recently wrote a [module](https://github.com/alexbooker/github-unfollow-everyone) for which I could not justify writing tests.

What's more, not everyone uses Travis. Some people use [AppVeyor](http://www.appveyor.com/docs/lang/nodejs-iojs) etc.

**Comment by arthurvr** [comment]
I'd personally prefer for this generator to stay minimal. It's really easy to just remove these after scaffolding, and 99% of the times you actually need tests and travis.

**Comment by alexbooker** [comment]
@arthurvr, I totally appreciate that point of view.

_If_ these proposed changes were accepted, all you would have to do is hit the \<ENTER> twice. 

At the moment, I have to:

1. Delete `mocha` from package.jso
- Delete `mocha` from `node_modules`
- Delete `travis.yml` file
- Remove travis badge from `readme.md'

Again, I _totally_ appreciate your point about minimalism and I understand that most people _do_ want tests and Travis (most but not 99%, I don't think... :stuck_out_tongue:) but this change would not impact you much and it would help me a lot.

**Comment by kevva** [comment]
If not 99%, it's really up there, and I'm not sure those few percents that don't need it justifies this change.

**Comment by alexbooker** [comment]
It is all good, guys. I can always maintain my own fork :wink:. Thank you for your consideration. (It is OK with me if you close this issue now.)

**Comment by sindresorhus** [comment]
I don't think I have any modules without tests. Happy to consider other improvements though :)
