### ISSUE TITLE
Prompt for description

### ISSUE THREAD

**Issue by thejameskyle** [sindresorhus/generator-nm#29]
Rather than manually enter it everywhere. Can be used for #28 as well.

**Comment by jamestalmage** [comment]
You may meet resistance on this one. See https://github.com/sindresorhus/generator-nm/pull/16

**Comment by sindresorhus** [comment]
Do you really ever know the description upfront? I sure don't.

**Comment by thejameskyle** [comment]
I often do because I'm pulling out existing functionality from something else. More often I don't know what I'm going to name it ahead of time.

**Comment by jamestalmage** [comment]
> More often I don't know what I'm going to name it ahead of time

That is kinda a reason not to do #28. Sure, you can rename a repo - but it would be better to get it right from the start.

**Comment by dawsonbotsford** [comment]
@thejameskyle I implemented the description format in my own fork, feel free to use my fork or implement this yourself, it is quite painless.

In addition, my fork is highly opinionated, so you never have to enter your username or email address (warning, tests failing with no plan to fix them).

Read the code here: https://github.com/dawsonbotsford/generator-db-nm/blob/master/app/index.js
Or try it `npm install --global generator-db-nm`

**Comment by sindresorhus** [comment]
> In addition, my fork is highly opinionated, so you never have to enter your username or email address 

You don't have to enter email address here, only username and website, and only the first time since it's persisted. Your "solution" seems to be to just [hardcode code it inline](https://github.com/dawsonbotsford/generator-db-nm/blob/59a58460f5c1fbcf5dbfb4c43807a9462d9c26e1/app/index.js#L10-L11)...

**Comment by dawsonbotsford** [comment]
@sindresorhus I did not realize that username and website were persisted in generator-nm. Thanks for pointing that out! My fork is certainly not intended to be used and shared, it just is personalized for myself with a few other things also like custom `package.json` keywords.

Cheers
