### ISSUE TITLE
Add `.nyc_output` and `coverage` to gitignore

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/generator-nm#34]

**Comment by SamVerschueren** [comment]
Don't really see the benefit of this as `nyc` isn't shipped with the generator. I hardly use code coverage, especially not in one-line modules, only for bigger projects.

**Comment by jamestalmage** [comment]
> nyc isn't shipped with the generator

Yeah, but AVA is, and if you do coverage with AVA, you probably are using `nyc`. Nothing included demands a `temp` directory either, but it is ignored as a matter of convenience.

**Comment by SamVerschueren** [comment]
I guess `nyc` indeed is the only coverage tool that can handle AVA today. But still, should we add noise to the generator for something that is probably used 1 out of 10 times?

**Comment by jamestalmage** [comment]
> 1 out of 10

In my case that is a way low ratio. I am basically the opposite end of the spectrum.

For that matter, why not do coverage for everything? `nyc` makes it so easy.

**Comment by sindresorhus** [comment]
@jamestalmage I open to adding a sub-generator that prompts for using `nyc` and adds it, but I don't see the point of adding stuff to a .gitignore that isn't actually used. PR welcome if anyone needs that.

I personally only use code coverage in larger modules.

**Comment by radiovisual** [comment]
I only use code coverage on larger projects as well, but I also use this generator as a starting point for large projects, so I would love to see this option added in. I always need to do the same type of manual edits (over and over) each time I want code coverage, and that type of manual repetition is what generators save you from.

I have sent a PR along these lines. Happy to discuss things further if my PR doesn't fit the vision.
