### ISSUE TITLE
Remembering user preferences

### ISSUE THREAD

**Issue by Semigradsky** [sindresorhus/generator-nm#4]
Why you aren't memorize user preferencies (GitHub username, URL of website)? This is nice feature ([from docs](http://yeoman.io/authoring/user-interactions.html)):
```javascript
this.prompt({
  type    : 'input',
  name    : 'username',
  message : 'What\'s your Github username',
  store   : true
}, callback);
```

**Comment by d10** [comment]
:+1:!
