### ISSUE TITLE
issue_template.md

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/generator-nm#44]
Seems like GitHub is really listening to the [dear-github](https://github.com/dear-github/dear-github) call. It's now possible to add an `issue_template.md` file to your repository in order to automatically prefill the issue textarea.

Example: https://github.com/owncloud/core/issues/new
More info: https://github.com/dear-github/dear-github/issues/125

Should we add this to `generator-nm`? Or maybe create a sub-generator with a multiple choice question where you can choose the blocks you want. A sub-generator might make more sense.

**Comment by sindresorhus** [comment]
Let's hold on and let them announce it officially first.

**Comment by SamVerschueren** [comment]
Sorry, excitement took over... :)

**Comment by sindresorhus** [comment]
I'm excited too ;)

**Comment by SamVerschueren** [comment]
Too bad you don't have an excitement cow in [cows](https://github.com/sindresorhus/cows). Not sure how it would look though.

https://www.youtube.com/watch?v=5KaltD0Z6ww

**Comment by sindresorhus** [comment]
An image will have to do.

![image](https://cloud.githubusercontent.com/assets/170270/13121249/30ad1c46-d5e4-11e5-820e-8d863ba42e03.png)

**Comment by SamVerschueren** [comment]
Oh my god! So much awesomeness!

**Comment by SamVerschueren** [comment]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by sindresorhus** [comment]
Yup. We first need to figure out what such templates should contain. At least the minimum.

I'd prefer to still wait a couple of weeks before finalizing this, but we can start planning now.

We could steal some inspiration from others:

- https://github.com/dear-github/dear-github/issues/125
- https://github.com/nodejs/node/pull/5291/files
- https://github.com/rails/rails/pull/23738
- https://github.com/dokku/dokku/blob/master/ISSUE_TEMPLATE.md
- https://github.com/capistrano/capistrano/pull/1583/files
- https://github.com/rubinius/rubinius/pull/3621/files
- https://github.com/ensime/ensime-server/pull/1301/files
- https://github.com/thumbor/thumbor/pull/668/files
- https://github.com/GoogleCloudPlatform/gcloud-common/issues/96
- https://github.com/dotnet/corefx/issues/6167
- https://github.com/summernote/summernote/pull/1694/files
- https://github.com/golang/go/issues/14365
- https://github.com/Microsoft/TypeScript/pull/7120/files
- https://github.com/chef/chef/pull/4590/files

**Comment by zenorocha** [comment]
Here are some other inspirations: https://github.com/devspace/awesome-github-templates ;)

**Comment by sindresorhus** [comment]
@zenorocha Of course an awesome list :p

Something that would be useful is to include examples of good sections to include. Not everyone has time to go through all of those links. Instead, show some of the best of all those.

**Comment by sindresorhus** [comment]
Closing as this repo is archived.
