### ISSUE TITLE
Make use of XO's overrides option and eslint-plugin-ava

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/generator-nm#45]
- turn on `esnext` for `test.js`
- use `eslint-plugin-ava` to lint tests

blocker: https://github.com/sindresorhus/xo/issues/88

**Comment by sindresorhus** [comment]
> turn on esnext for test.js

:+1: 

> use eslint-plugin-ava to lint tests

I was actually planning to bundle `eslint-plugin-ava` in XO.

**Comment by sindresorhus** [comment]
Closing as the `eslint` option will be enabled by default in the next XO version and `eslint-plugin-ava` is included in XO by default.
