### ISSUE TITLE
Prompt for module description

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/generator-nm#57]
This is a feature request to add a prompt asking for the project description. If no description is provided, then the default is to use one of the `superb` phrases like `'my awesome module'`

The argument is that providing a prompt for the description saves the user time by saving them from lots of keystrokes/mouse clicks and moving in and out of different files.

For example:

### To update the description **WITHOUT** a prompt:

- **2 Mouse clicks:** Click to open package.json.
- **2 Mouse clicks:** Click [and/or drag] to highlight "superb" placeholder in `package.json`.
- **Type the description** (Can be any length)
- **2 Keyboard events:** Save the `package.json` file with <kbd>CMD/CTRL</kbd> + <kbd>S</kbd>.
- **2 Mouse clicks:** Highlight the description for pasting in `readme.md`
- **2 Mouse clicks:** Open the `readme.md` file.
- **2 Mouse clicks:** Click [and/or drag] to highlight "superb" placeholder in `readme.md`
- **2 Keyboard events:** Paste the description with <kbd>CMD/CTRL</kbd> + <kbd>V</kbd>.
- **2 Keyboard events:** Save the `package.json` file with <kbd>CMD/CTRL</kbd> + <kbd>S</kbd>.

**TOTAL INTERACTION EVENTS:** *16 

The example above uses the "best case scenario", because if the user doesn't copy-paste the description after typing it once, then they find themselves typing it twice, or cycling back to the file where the description was first typed, just to copy, switch back to another file and paste, adding a lot more extra interaction events.
  
---------------

### To update the description **WITH** a prompt:

- **Type the description at the prompt** (Can be any length)
- **1 Keyboard event:** Hit <kbd>Enter</kbd> to accept the prompt.

**TOTAL INTERACTION EVENTS:** *1

---------------

You can see how prompting for the description saves time!

For those looking for the default behavior (the `superb` placeholder), they would just have to enter a blank description, costing them one extra keystroke, at the expense of having the ability to save a minimum of 16 keystokes by entering the project description at the prompt. 

---------------

\* does not include the typing of the description

**Comment by sindresorhus** [comment]
Already discussed in https://github.com/sindresorhus/generator-nm/issues/29, but seems many want this, so sure. Pull request welcome :)

**Comment by radiovisual** [comment]
Oh, sorry, I didn't see the archived discussions in #29 and #16, but now that I have read them, I see that a common argument is that some won't know the description beforehand (which is usually true for me on large modules, where I keep having to change the wording of the description), and totally understandable, but on many of my smaller modules (which make up the majority for me), I know exactly what the description is going to say as I am scaffolding out the module, and I find myself running into the tedium of all those 16+ extra steps to replace the placeholder description. 

So, IMO, adding in one extra keystroke at the prompt to keep the placeholder ("superb") description, is a small price to pay for the added benefit of being able to update the description in one step. 

I can work on this PR today. 😄
