### ISSUE TITLE
Hyphenated or punctuated superb descriptions cause test to fail 

### ISSUE THREAD

**Issue by radiovisual** [sindresorhus/generator-nm#59]
As pointed out by @JonnyBurger in [PR #58](https://github.com/sindresorhus/generator-nm/pull/58), there is a small chance (~5%) that the `RegExp` in the [unit tests for the prompt description](https://github.com/sindresorhus/generator-nm/blob/master/test.js#L136-L137):

```js
"My (\w)+ module"
``` 
might cause the test to fail on spaced, hyphenated or punctuated superb values like:

```
"awe-inspiring",
"bee's knees",
"cat's pajamas",
```
So I propose a slightly more generic, and forgiving RegExp like:

```js
/My (.)+ module/
```

Which would future-proof itself to any other entries to the superb module that might involve punctuation or multiple words.

**Comment by sindresorhus** [comment]
👍
