### ISSUE TITLE
Add `npm version` badge?

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/generator-nm#62]
I find it pretty useful to have a badge linking to the `npm` page on GitHub on repos, like [![version](https://img.shields.io/npm/v/ava.svg)](http://npm.im/ava).
I like it also because it allows me to click on it, and be redirected to the npm page, which I use for instance to see the number of downloads of some/my packages. Without it, I have to go find it on npm to find it.

What do you think about adding one?

**Comment by sindresorhus** [comment]
Hmm. I can't remember the last time I needed to go to the npm page. Or even wanted to. Their Markdown rendering is so broken and inconsistent with GitHub.

I don't add new badges lightly. Download numbers are really the only useful thing there. I've been thinking about instead creating a Chrome extension that embeds the download stats in the GitHub UI.

**Comment by jfmengels** [comment]
> Their Markdown rendering is so broken

Yep. I wanted to file a few issues, but never got to it. I'm hoping they're aware of it and just have more urgent things to work on.

I'd be interested in the Chrome extension :)
Since I mostly use the npm page to find out the download count, I think that would probably be enough for me as a user. Don't know what the rest of the world use it for though.

**Comment by sindresorhus** [comment]
> Yep. I wanted to file a few issues, but never got to it. I'm hoping they're aware of it and just have more urgent things to work on.

I've tried to fix it so many times. Just gave up.

**Comment by jfmengels** [comment]
Feel free to close this issue if you don't like the idea of a new badge.
Let me know if you work on that extension ;)

**Comment by sindresorhus** [comment]
I'll keep it open for more opinions and so I don't forget about the extension (Feel free to do it yourself btw).

**Comment by sholladay** [comment]
I don't get a lot of usefulness out of it when authors include an npm version badge. Sure, it's nice as a quick link to the relevant npm page. But a browser extension would work well too and can be generic and applied to all repos.

The only other supposed benefit is seeing the current release number very quickly. But you can get this info easily enough by clicking "Releases". Yes, it is technically possible they have git tags that aren't published on npm, but this is very rare.

In some ways, I find the npm version misleading when browsing GitHub. Some projects - mine included - tend to leave things sitting on `master` for a while before releasing, so the state of the codebase on GitHub can be very different from what is published on npm. And knowing the version number alone doesn't tell you anything about what has changed, only the Releases tab can help you with that.

**Comment by sindresorhus** [comment]
Yeah. Not going to add it.
