### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by LasaleFamine** [sindresorhus/generator-nm#67]
Have you thought about asking the user of the use of `yarn` instead of `npm`?

**Comment by clemtrek** [comment]
It Would Really Be A Help.

**Comment by sindresorhus** [comment]
I'm gonna pass on this. I don't use Yarn.

**Comment by LasaleFamine** [comment]
Actually I understand, in fact I made my version of the generator. 

Anyway, I'm wondering why you are not using Yarn, but maybe this is a question for an AMA. 👍

**Comment by sindresorhus** [comment]
> Actually I understand, in fact I made my version of the generator, heavily inspired to this one of your.

👍 It's meant to be forkable. Everyone has their own preferences.

> Anyway, I'm wondering why you are not using Yarn, but maybe this is a question for an AMA.

👍 Good idea.
