### ISSUE TITLE
I made a thing.

### ISSUE THREAD

**Issue by perryprog** [sindresorhus/generator-nm#68]
I made [a fork](https://github.com/perryprog/generator-nm) for my own uses (spaces > tabs, other things) and I ended up adding some things that may be good in this repo. It would be really cool if you could take a look at it!

In case you're interested in merging, I have a [branch called ew-tabs](https://github.com/perryprog/generator-nm/tree/ew-tabs) 😉, which has tabs and that sort of thing. 

The main feature of the fork is the addition of auto creating a GitHub repo, and auto push to the GitHub repo, along with enabling Travis. This would fix #28. Screenshot:

<img width="2004" alt="screen shot 2017-05-24 at 3 57 18 pm" src="https://cloud.githubusercontent.com/assets/12972285/26422961/c3423444-4099-11e7-9cbd-129d1ab33bab.png">

I did not touch the tests, and they are currently failing. If you want, I can *try* to fix them, however I've never written tests for a Yeoman generator.

**Comment by radiovisual** [comment]
@perryprog See the discussion in #28, it is related to your ideas of automatically creating a GitHub repo.

**Comment by sindresorhus** [comment]
Nice! I'm happy to link to it from the readme if you do a PR, but I'm not interested in adding more features to the generator at this point.

**Comment by perryprog** [comment]
I don't think there's any need to add a link for it, as it's at this point unmaintained—it'd probably be better to have just the one version.
