### ISSUE TITLE
generate binaries for cli?

### ISSUE THREAD

**Issue by mastilver** [sindresorhus/generator-nm#72]
Would you consider a PR to use `pkg` as a `prerelease` script to generate binaries for non-node users
The binaries could be either available on:
- https://unpkg.com/ (easy as we just need to publish the binaries)
- github releases (a bit more complex as it will involve using https://developer.github.com/v3/repos/releases/#upload-a-release-asset and making sure there is a release on github (it could clash with `np`))

**Comment by sindresorhus** [comment]
Nah, that's just creating lots of complications for a problem I don't have. There are many downsides in packaging a Node.js binary. I don't think this is something most people will need either. It's super easy to install Node.js. Would probably be a better solution to create a tool that can download Node.js CLI's and package them on-demand for people that refuse to install Node.js. It shouldn't be the responsibility of package authors.
