### ISSUE TITLE
Support for `ava`

### ISSUE THREAD

**Issue by 9965buzzer** [sindresorhus/generator-nm#8]
Hello @sindresorhus. I have a question for you. Would you mind adding an option to use the `ava` testing framework? I see some people including you and kevva using it all over the place and it looks really good. Or is there some separate generator-ava-node-module? Would be interested to hear that. I would like to be able to use a ava on my personal projects so this would help. I tried to PR for this but a search and replace for `macha`  to `ava` didn't help.Thanks in advance. If you would like me to do a pull request for this update, can you point me in the right direction? I can't git commit it seems? (I'm on windows). I would like to also cc @kevva in this ticket as he seems to be using the framework as well. Thanks for creating this generator! I always wanted something more advanced then yeoman's default generator-node.

**Comment by arthurvr** [comment]
Can you try to give the PR a clear, shorter, on-topic title and instead extend the actual PR description?

**Comment by kevva** [comment]
It's going to be the standard testing framework when `ava` is a little more stable. Hopefully soon.

**Comment by sindresorhus** [comment]
That's the plan, but `ava` isn't ready for public use **yet**. We're only using it on our own modules to battle-test it. You're of course free to use it, but you won't get any support and there might be bugs.

**Comment by 9965buzzer** [comment]
Thanks for the response. Sorry about that @arthurvr. I think I've edited it now?

**Comment by sindresorhus** [comment]
Done in 1.7.0 :)

**Comment by ragingwind** [comment]
Yai, finally. Thanks for great job
