### ISSUE TITLE
TypeScript equivalent?

### ISSUE THREAD

**Issue by abrkn** [sindresorhus/generator-nm#81]
Looking for a TypeScript equivalent of this repo.

**Comment by sindresorhus** [comment]
I don’t have this yet as I’m not yet happy about my TypeScript setup.

Someone did port it to TS: https://github.com/EdJoPaTo/typescript-node-module-boilerplate But no guarantees about the quality.

You could also take a look at one of my TS projects: https://github.com/sindresorhus/got/blob/master/package.json

**Comment by rigwild** [comment]
I'm doing exactly that! https://github.com/rigwild/generator-nm-typescript

**Comment by abrkn** [comment]
> I'm doing exactly that! [rigwild/generator-nm-typescript](https://github.com/rigwild/generator-nm-typescript)
> 
> * TypeScript
> * Yarn
> * Node module OR CLI (not both in same repo)
> * Github Actions instead of Travis
> * more..

Looks great. I'll give it a shot for my next module.

**Comment by sindresorhus** [comment]
Closing as this repo is archived.
