### ISSUE TITLE
Descriptions containing unicode characters gets encoded

### ISSUE THREAD

**Issue by rigwild** [sindresorhus/generator-nm#82]
After some testing, I got unlucky with [superb](https://github.com/sindresorhus/superb#readme) with a description containing an apostrophe.

Yeoman seems to encode Unicode characters to be HTML-safe.

`My cat's meow module`

`package.json`:
```json
{
  "description": "My cat&#39;s meow module"
}
```

`readme.md`:
```
> My cat&#39;s meow module
```

It does not break the `package.json` file, nor the readme rendering though.

Related: #59 #60

**Comment by sindresorhus** [comment]
This is an edge-case, so I'm most likely not going to look into this. But a PR is always welcome.

**Comment by rigwild** [comment]
did some testing, checked which chars would break `package.json`

Tested:
```
& é ~ " # ' { ( [ - | è ` _ \ ç ^ à @ ) ] ° = + } ¨ $ £ ¤ ù % * µ < > , ? ; . : / ! § a ã ä â à
```

Ones that gets HTML-encoded:
```
& " ' < >
```

One that does not get encoded but still break
```
\
```

Emojis seems to work as expected.
There will always be some random unicode chars that will always break it, but that's too edgy, no one really care.

Escaping is not enough (they still get converted by yeoman when using `fs.copyTpl`

I can do a PR that simply replace these with a space.
