### ISSUE TITLE
Use c8 instead of nyc for code coverage

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/generator-nm#87]
Inspired by: https://github.com/avajs/ava/pull/2843

I'm actually having problems with [nyc](https://github.com/istanbuljs/nyc) while on the [AVA 4](https://github.com/avajs/ava/releases/tag/v4.0.0-rc.1) release candidate, where the coverage table is empty, presumably having something to do with AVA now using worker threads instead of child processes. I tried [c8](https://github.com/bcoe/c8) and it just works, including on AVA 3.

One caveat: c8 seems to be quite a bit slower, at least in a medium sized app where it adds almost 30 seconds to `npm test` compared to without coverage, while nyc adds less than 10 seconds (including on AVA 3 where it works properly).

**Comment by sindresorhus** [comment]
Yeah, I want to switch to `c8`.

**Comment by sindresorhus** [comment]
> One caveat: c8 seems to be quite a bit slower, at least in a medium sized app where it adds almost 30 seconds to npm test compared to without coverage, while nyc adds less than 10 seconds (including on AVA 3 where it works properly).

I'm ok with that. It will probably be improved in the future.

**Comment by sindresorhus** [comment]
Closing as this repo is archived.
